local M = {}

local function hl(name, opts)
	vim.api.nvim_set_hl(0, name, opts)
end

function M.setup(c)
	-- Telescope
	hl("TelescopeNormal", { fg = c.fg, bg = c.sidebar_bg })
	hl("TelescopeBorder", { fg = c.panel_border, bg = c.sidebar_bg })
	hl("TelescopePromptNormal", { fg = c.input_fg, bg = c.input_bg })
	hl("TelescopePromptBorder", { fg = c.panel_border, bg = c.input_bg })
	hl("TelescopePromptTitle", { fg = c.statusline_fg, bg = c.statusline_bg })
	hl("TelescopePreviewTitle", { fg = c.badge_fg, bg = c.badge_bg })
	hl("TelescopeResultsTitle", { fg = c.sidebar_fg, bg = c.sidebar_bg })
	hl("TelescopeSelection", { bg = c.list_active })
	hl("TelescopeSelectionCaret", { fg = c.tag })
	hl("TelescopeMultiSelection", { fg = c.tag })
	hl("TelescopeMatching", { fg = c.tag })
	hl("TelescopeResultsDiffAdd", { fg = c.number })
	hl("TelescopeResultsDiffChange", { fg = c.warn })
	hl("TelescopeResultsDiffDelete", { fg = c.regex })

	-- WhichKey
	hl("WhichKey", { fg = c.function_fg })
	hl("WhichKeyGroup", { fg = c.tag })
	hl("WhichKeySeparator", { fg = c.comment })
	hl("WhichKeyDesc", { fg = c.fg })
	hl("WhichKeyFloat", { bg = c.sidebar_bg })
	hl("WhichKeyBorder", { fg = c.panel_border, bg = c.sidebar_bg })
	hl("WhichKeyTitle", { fg = c.statusline_fg, bg = c.statusline_bg })

	-- Neo-tree
	hl("NeoTreeNormal", { fg = c.sidebar_fg, bg = c.sidebar_bg })
	hl("NeoTreeNormalNC", { fg = c.sidebar_fg, bg = c.sidebar_bg })
	hl("NeoTreeIndentMarker", { fg = c.whitespace })
	hl("NeoTreeRootName", { fg = c.fg, bold = true })
	hl("NeoTreeDirectoryName", { fg = c.tag })
	hl("NeoTreeFileIcon", { fg = c.sidebar_fg })
	hl("NeoTreeTitleBar", { fg = c.statusline_fg, bg = c.statusline_bg })
	hl("NeoTreeFloatNormal", { bg = c.sidebar_bg })
	hl("NeoTreeFloatBorder", { fg = c.panel_border, bg = c.sidebar_bg })
	hl("NeoTreeCursorLine", { bg = c.line_bg })
	hl("NeoTreeGitAdded", { fg = c.number })
	hl("NeoTreeGitDeleted", { fg = c.regex })
	hl("NeoTreeGitModified", { fg = c.warn })
	hl("NeoTreeGitUnstaged", { fg = c.warn })
	hl("NeoTreeGitStaged", { fg = c.number })
	hl("NeoTreeGitUntracked", { fg = c.comment })
	hl("NeoTreeGitConflict", { fg = c.error })
	hl("NeoTreeDotfile", { fg = c.line_nr })
	hl("NeoTreeSymbolicLinkTarget", { fg = c.uri })
	hl("NeoTreeDimText", { fg = c.line_nr })

	-- Gitsigns
	hl("GitSignsAdd", { fg = c.number, bg = c.bg })
	hl("GitSignsChange", { fg = c.warn, bg = c.bg })
	hl("GitSignsDelete", { fg = c.regex, bg = c.bg })
	hl("GitSignsChangedelete", { fg = c.warn, bg = c.bg })
	hl("GitSignsTopdelete", { fg = c.regex, bg = c.bg })
	hl("GitSignsAddNr", { fg = c.number })
	hl("GitSignsChangeNr", { fg = c.warn })
	hl("GitSignsDeleteNr", { fg = c.regex })
	hl("GitSignsChangedeleteNr", { fg = c.warn })

	-- mini.statusline
	hl("MiniStatuslineModeNormal", { fg = c.badge_fg, bg = c.badge_bg })
	hl("MiniStatuslineModeInsert", { fg = c.badge_fg, bg = c.badge_bg })
	hl("MiniStatuslineModeVisual", { fg = c.badge_fg, bg = c.badge_bg })
	hl("MiniStatuslineModeReplace", { fg = c.badge_fg, bg = c.error })
	hl("MiniStatuslineModeCommand", { fg = c.badge_fg, bg = c.badge_bg })
	hl("MiniStatuslineModeOther", { fg = c.badge_fg, bg = c.sidebar_bg })
	hl("MiniStatuslineDevinfo", { fg = c.fg, bg = c.tab_inactive_bg })
	hl("MiniStatuslineFileinfo", { fg = c.fg, bg = c.tab_inactive_bg })
	hl("MiniStatuslineFilename", { fg = c.sidebar_fg, bg = c.tab_inactive_bg })
	hl("MiniStatuslineInactive", { fg = c.tab_inactive_fg, bg = c.tab_inactive_bg })

	-- todo-comments
	hl("TodoFgTODO", { fg = c.todo })
	hl("TodoBgTODO", { bg = c.todo, fg = c.bg })
	hl("TodoFgFIX", { fg = c.error })
	hl("TodoBgFIX", { bg = c.error, fg = c.bg })
	hl("TodoFgHACK", { fg = c.warn })
	hl("TodoBgHACK", { bg = c.warn, fg = c.bg })
	hl("TodoFgWARN", { fg = c.warn })
	hl("TodoBgWARN", { bg = c.warn, fg = c.bg })
	hl("TodoFgPERF", { fg = c.number })
	hl("TodoBgPERF", { bg = c.number, fg = c.bg })
	hl("TodoFgNOTE", { fg = c.info })
	hl("TodoBgNOTE", { bg = c.info, fg = c.bg })
	hl("TodoFgTEST", { fg = c.hint })
	hl("TodoBgTEST", { bg = c.hint, fg = c.bg })
	hl("TodoSignTODO", { fg = c.todo })
	hl("TodoSignFIX", { fg = c.error })
	hl("TodoSignHACK", { fg = c.warn })
	hl("TodoSignWARN", { fg = c.warn })
	hl("TodoSignPERF", { fg = c.number })
	hl("TodoSignNOTE", { fg = c.info })
	hl("TodoSignTEST", { fg = c.hint })

	-- blink.cmp / nvim-cmp
	hl("BlinkCmpMenu", { fg = c.dropdown_fg, bg = c.dropdown_bg })
	hl("BlinkCmpMenuSelection", { bg = c.list_active, fg = c.dropdown_fg })
	hl("BlinkCmpScrollBarThumb", { bg = c.scrollbar })
	hl("BlinkCmpScrollBarGutter", { bg = c.list_inactive })
	hl("BlinkCmpDoc", { bg = c.sidebar_bg })
	hl("BlinkCmpDocBorder", { fg = c.panel_border })
	hl("BlinkCmpLabel", { fg = c.fg })
	hl("BlinkCmpLabelDeprecated", { fg = c.line_nr })
	hl("BlinkCmpLabelDescription", { fg = c.comment })
	hl("BlinkCmpLabelMatch", { fg = c.tag })
	hl("BlinkCmpLabelDetail", { fg = c.comment })
	hl("BlinkCmpKindKeyword", { fg = c.keyword })
	hl("BlinkCmpKindVariable", { fg = c.variable })
	hl("BlinkCmpKindConstant", { fg = c.constant })
	hl("BlinkCmpKindReference", { fg = c.variable })
	hl("BlinkCmpKindValue", { fg = c.constant })
	hl("BlinkCmpKindFunction", { fg = c.function_fg })
	hl("BlinkCmpKindMethod", { fg = c.function_fg })
	hl("BlinkCmpKindConstructor", { fg = c.constructor })
	hl("BlinkCmpKindField", { fg = c.field })
	hl("BlinkCmpKindProperty", { fg = c.property })
	hl("BlinkCmpKindClass", { fg = c.type_fg })
	hl("BlinkCmpKindInterface", { fg = c.type_fg })
	hl("BlinkCmpKindStruct", { fg = c.type_fg })
	hl("BlinkCmpKindModule", { fg = c.namespace })
	hl("BlinkCmpKindUnit", { fg = c.type_fg })
	hl("BlinkCmpKindFile", { fg = c.tag })
	hl("BlinkCmpKindFolder", { fg = c.tag })
	hl("BlinkCmpKindEnum", { fg = c.type_fg })
	hl("BlinkCmpKindEnumMember", { fg = c.constant })
	hl("BlinkCmpKindColor", { fg = c.special })
	hl("BlinkCmpKindEvent", { fg = c.special })
	hl("BlinkCmpKindOperator", { fg = c.operator })
	hl("BlinkCmpKindTypeParameter", { fg = c.type_fg })
	hl("BlinkCmpKindSnippet", { fg = c.special })
	hl("BlinkCmpKindText", { fg = c.fg })
	hl("BlinkCmpKindCopilot", { fg = c.number })

	-- fidget.nvim
	hl("FidgetTitle", { fg = c.tag, bold = true })
	hl("FidgetTask", { fg = c.fg })

	-- lazy.nvim
	hl("LazyButton", { fg = c.badge_fg, bg = c.badge_bg })
	hl("LazyButtonActive", { fg = c.badge_fg, bg = c.statusline_bg })
	hl("LazyReasonEvent", { fg = c.comment })
	hl("LazyReasonStart", { fg = c.tag })
	hl("LazyReasonSource", { fg = c.fg })
	hl("LazyReasonImport", { fg = c.info })
	hl("LazyReasonRuntime", { fg = c.keyword })
	hl("LazyReasonPlugin", { fg = c.fg })
	hl("LazySpecial", { fg = c.number })

	-- nvim-treesitter-context
	hl("TreesitterContext", { bg = c.line_bg })
	hl("TreesitterContextLineNumber", { fg = c.active_line_nr, bg = c.line_bg })

	-- Indent-blankline
	hl("IblIndent", { fg = c.indent_guide })
	hl("IblScope", { fg = c.indent_active })
	hl("IblWhitespace", { fg = c.whitespace })

	-- Noice
	hl("NoiceCursor", { fg = c.bg, bg = c.cursor })
	hl("NoiceFormatTitle", { fg = c.tag, bold = true })
	hl("NoiceFormatConfirm", { fg = c.number })
	hl("NoiceLspProgressTitle", { fg = c.tag })

	-- Dap
	hl("DapStopped", { fg = c.number })
	hl("DapBreakpoint", { fg = c.error })
	hl("DapLogPoint", { fg = c.info })

	-- Flash
	hl("FlashLabel", { fg = c.bg, bg = c.warn })
	hl("FlashMatch", { bg = c.search })
	hl("FlashCurrent", { bg = c.search_current })

	-- alpha-nvim (dashboard)
	hl("AlphaHeader", { fg = c.tag })
	hl("AlphaHeaderLabel", { fg = c.function_fg })
	hl("AlphaButtons", { fg = c.fg })
	hl("AlphaShortcut", { fg = c.tag })
	hl("AlphaFooter", { fg = c.comment })

	-- notify
	hl("NotifyERRORBorder", { fg = c.error })
	hl("NotifyWARNBorder", { fg = c.warn })
	hl("NotifyINFOBorder", { fg = c.info })
	hl("NotifyDEBUGBorder", { fg = c.comment })
	hl("NotifyTRACEBorder", { fg = c.special })
	hl("NotifyERRORIcon", { fg = c.error })
	hl("NotifyWARNIcon", { fg = c.warn })
	hl("NotifyINFOIcon", { fg = c.info })
	hl("NotifyDEBUGIcon", { fg = c.comment })
	hl("NotifyTRACEIcon", { fg = c.special })
	hl("NotifyERRORTitle", { fg = c.error })
	hl("NotifyWARNTitle", { fg = c.warn })
	hl("NotifyINFOTitle", { fg = c.info })
	hl("NotifyDEBUGTitle", { fg = c.comment })
	hl("NotifyTRACETitle", { fg = c.special })

	-- Navic / Breadcrumb
	hl("NavicIconsFile", { fg = c.tag })
	hl("NavicIconsModule", { fg = c.namespace })
	hl("NavicIconsNamespace", { fg = c.namespace })
	hl("NavicIconsPackage", { fg = c.namespace })
	hl("NavicIconsClass", { fg = c.type_fg })
	hl("NavicIconsMethod", { fg = c.function_fg })
	hl("NavicIconsProperty", { fg = c.property })
	hl("NavicIconsField", { fg = c.field })
	hl("NavicIconsConstructor", { fg = c.constructor })
	hl("NavicIconsEnum", { fg = c.type_fg })
	hl("NavicIconsInterface", { fg = c.type_fg })
	hl("NavicIconsFunction", { fg = c.function_fg })
	hl("NavicIconsVariable", { fg = c.variable })
	hl("NavicIconsConstant", { fg = c.constant })
	hl("NavicIconsString", { fg = c.string })
	hl("NavicIconsNumber", { fg = c.number })
	hl("NavicIconsBoolean", { fg = c.boolean })
	hl("NavicIconsArray", { fg = c.operator })
	hl("NavicIconsObject", { fg = c.type_fg })
	hl("NavicIconsKey", { fg = c.property })
	hl("NavicIconsNull", { fg = c.constant })
	hl("NavicIconsEnumMember", { fg = c.constant })
	hl("NavicIconsStruct", { fg = c.type_fg })
	hl("NavicIconsEvent", { fg = c.special })
	hl("NavicIconsOperator", { fg = c.operator })
	hl("NavicIconsTypeParameter", { fg = c.type_fg })
	hl("NavicText", { fg = c.fg })
	hl("NavicSeparator", { fg = c.delimiter })

	-- Trouble
	hl("TroubleNormal", { fg = c.fg, bg = c.sidebar_bg })
	hl("TroubleSignError", { fg = c.error })
	hl("TroubleSignWarn", { fg = c.warn })
	hl("TroubleSignInfo", { fg = c.info })
	hl("TroubleSignHint", { fg = c.hint })
	hl("TroubleSignOther", { fg = c.comment })
	hl("TroubleCount", { fg = c.badge_fg, bg = c.badge_bg })
	hl("TroubleSource", { fg = c.comment })
	hl("TroubleIndent", { fg = c.whitespace })
	hl("TroubleFoldIcon", { fg = c.line_nr })
	hl("TroubleText", { fg = c.fg })
	hl("TroubleTextError", { fg = c.error })
	hl("TroubleTextWarn", { fg = c.warn })
	hl("TroubleTextInfo", { fg = c.info })
	hl("TroubleTextHint", { fg = c.hint })
	hl("TroublePreview", { fg = c.fg, bg = c.line_bg })
end

return M
