vim.keymap.set("n", "<leader>d", "", { desc = "[d]iff View" })
vim.keymap.set("n", "<leader>do", ":DiffviewOpen<CR>", { desc = "[d]iff View [o]pen" })
vim.keymap.set("n", "<leader>dc", ":DiffviewClose<CR>", { desc = "[d]iff View [c]lose" })
vim.keymap.set("n", "<leader>df", ":DiffviewFileHistory<CR>", { desc = "[d]iff View [f]ile History" })
vim.keymap.set("n", "<leader>dr", ":DiffviewRefresh<CR>", { desc = "[d]iff View [r]efresh" })
