vim.keymap.set("n", "<leader>h", "", { desc = "[H]arpoon" })
vim.keymap.set("n", "<leader>hm", function()
	require("harpoon.ui").toggle_quick_menu()
end, { desc = "[H]arpoon [M]enu" })
vim.keymap.set("n", "<leader>ha", function()
	require("harpoon.mark").add_file()
end, { desc = "[H]arpoon [A]dd" })

vim.keymap.set("n", "<M-o>", function()
	require("harpoon.ui").nav_next()
end, { desc = "Harpoon Next" })
vim.keymap.set("n", "<M-i>", function()
	require("harpoon.ui").nav_prev()
end, { desc = "Harpoon Previous" })
